# Generated by Django 5.0.6 on 2024-07-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0002_alter_student_department_alter_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('lecturerName', models.CharField(max_length=70)),
                ('number', models.EmailField(max_length=90)),
                ('email', models.EmailField(max_length=90)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fullName',
            new_name='studentName',
        ),
    ]
