# Generated by Django 5.0.6 on 2024-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0004_course_alter_lecturer_number_teaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='number',
            field=models.CharField(max_length=9),
        ),
    ]
