# Generated by Django 5.0.6 on 2024-07-08 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0005_alter_lecturer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('recordID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=7)),
                ('presentCount', models.PositiveIntegerField(default=0)),
                ('absentCount', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.student')),
            ],
        ),
    ]
