# Generated by Django 5.0.6 on 2024-07-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0007_remove_attendance_absentcount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.course')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.student')),
            ],
            options={
                'unique_together': {('studentID', 'courseID')},
            },
        ),
    ]
