# Generated by Django 5.0.6 on 2024-07-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0009_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
