# Generated by Django 5.0.7 on 2024-07-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0010_alter_lecturer_password_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetableID', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['day', 'start_time', 'course'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['recordID', 'student__studentName', 'course__courseName', '-date']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['courseID', 'courseName']},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'ordering': ['userID', 'lecturerName']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['userID', 'studentName', 'department', 'level']},
        ),
        migrations.AddField(
            model_name='student',
            name='fingerprint_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='number',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'course'], name='bioattend_a_student_f0ff65_idx'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.course'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.lecturer'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['day', 'course'], name='bioattend_t_day_5f69e1_idx'),
        ),
    ]
