# Generated by Django 5.0.6 on 2024-07-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=255)),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
