# Generated by Django 5.0.7 on 2024-07-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('administratorID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('recordID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=7)),
            ],
            options={
                'ordering': ['recordID', 'student__user__user_name', 'course__courseName', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=70)),
                ('courseCode', models.CharField(max_length=7)),
                ('department', models.CharField(choices=[('computer', 'Computer Engineering'), ('electrical', 'Electrical Engineering'), ('mechanical', 'Mechanical Engineering'), ('civil', 'Civil Engineering')], max_length=50)),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=20)),
            ],
            options={
                'ordering': ['courseID', 'courseName'],
            },
        ),
        migrations.CreateModel(
            name='Enrolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturerID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=9, unique=True)),
                ('department', models.CharField(choices=[('computer', 'Computer Engineering'), ('electrical', 'Electrical Engineering'), ('mechanical', 'Mechanical Engineering'), ('civil', 'Civil Engineering')], max_length=50)),
                ('level', models.CharField(choices=[('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400'), ('500', 'Level 500'), ('550', 'Level 550')], max_length=10)),
            ],
            options={
                'ordering': ['user__user_name', 'department', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetableID', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['day', 'start_time', 'course'],
            },
        ),
    ]
