# Generated by Django 5.0.7 on 2024-07-14 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bioattend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.course'),
        ),
        migrations.AddField(
            model_name='enrolls',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.course'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrolls',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.student'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.course'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='lecturerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.lecturer'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.course'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.lecturer'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolls',
            unique_together={('studentID', 'courseID')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'course'], name='bioattend_a_student_f0ff65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('lecturerID', 'courseID')},
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['day', 'course'], name='bioattend_t_day_5f69e1_idx'),
        ),
    ]
