# Generated by Django 5.0.7 on 2024-07-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.CharField(choices=[('ground_floor', 'FET Ground Floor'), ('hall1', 'FET Hall 1'), ('hall2', 'FET Hall 2')], max_length=50),
        ),
    ]
