# Generated by Django 5.0.6 on 2024-07-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0003_lecturer_rename_fullname_student_studentname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=70)),
                ('courseCode', models.CharField(max_length=7)),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='number',
            field=models.CharField(max_length=90),
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.course')),
                ('lecturerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.lecturer')),
            ],
            options={
                'unique_together': {('lecturerID', 'courseID')},
            },
        ),
    ]
