# Generated by Django 5.0.6 on 2024-07-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0006_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absentCount',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='presentCount',
        ),
    ]
