# Generated by Django 5.0.6 on 2024-07-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0008_enrolls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['studentName', 'department', 'level']},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['userID', 'matricule'], name='bioattend_s_userID_fe5a5d_idx'),
        ),
    ]
