# Generated by Django 5.0.7 on 2024-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0011_timetable_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10),
        ),
    ]
