# Generated by Django 5.0.7 on 2024-07-11 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0012_alter_timetable_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fingerprint_data',
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_data', models.BinaryField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioattend.student')),
            ],
            options={
                'unique_together': {('student',)},
            },
        ),
    ]
