# Generated by Django 5.0.7 on 2024-07-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioattend', '0013_remove_student_fingerprint_data_fingerprint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fingerprint',
        ),
    ]
